# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2017, 3, 19, 15, 29, 43, 978000))),
                ('date_formed', models.DateField(blank=True, null=True)),
                ('date_disbanded', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
